name: Build and Deploy

on:
  push:
    branches: [main]


jobs:
  deploy:
   runs-on: ubuntu-latest
   steps: 
    - name: Deploy app
      uses: appleboy/ssh-action@v0.1.2
      with: 
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}


        script: |
          mkdir test
          cd test
          git clone https://github.com/craig-glass/Deploy_Digitalocean.git
          echo "Deployment successful!!"